package com.aurionpro.app.entity;

public enum ActionType {
    USER_REGISTERED, USER_LOGIN_OTP, USER_LOGIN_PASSWORD, USER_LOGOUT,
    PASSWORD_RESET_REQUEST, PASSWORD_RESET_SUCCESS,
    PROFILE_UPDATED, PROFILE_PICTURE_UPLOADED, PROFILE_PICTURE_DELETED,
    TICKET_BOOKED, TICKET_CANCELLED,
    WALLET_RECHARGE_INITIATED, WALLET_RECHARGE_COMPLETED,
    WALLET_PAYMENT_DEBIT, WALLET_REFUND_ISSUED,
    VALIDATION_ENTRY, VALIDATION_EXIT, VALIDATION_FAILED,
    STATION_CREATED, STATION_UPDATED, STATION_DELETED,
    ROUTE_CREATED, ROUTE_UPDATED, ROUTE_DELETED,
    FARERULE_CREATED, FARERULE_UPDATED, FARERULE_DELETED,
    STAFF_USER_CREATED
}